version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: eduportal-postgres
    environment:
      POSTGRES_DB: assignment_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: src/AssignmentSystem.Api/Dockerfile
    container_name: eduportal-backend
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=assignment_system;Username=postgres;Password=postgrespassword
      - Jwt__Key=SUPER_SECRET_ENTERPRISE_KEY_MUST_BE_AT_LEAST_256_BITS_LONG_FOR_EDUPORTAL
      - Jwt__Issuer=AssignmentSystem.Api
      - Jwt__Audience=AssignmentSystem.Client
      - Cors__AllowedOrigins__0=http://localhost:3000
    ports:
      - "5215:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eduportal-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5215
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
